### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by schlichtanders** [sheldonjuncker/node-kubycat#4]
I getting error trying kubycat on my linux machine

```bash

TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at new NodeError (node:internal/errors:405:5)
    at Object.watch (node:fs:2416:11)
    at Kubycat.watchFiles (/home/myhome/.npm-packages/lib/node_modules/kubycat/dist/cjs/Kubycat.js:56:46)
    at Kubycat.<anonymous> (/home/myhome/.npm-packages/lib/node_modules/kubycat/dist/cjs/Kubycat.js:90:18)
    at Generator.next (<anonymous>)
    at /home/myhome/.npm-packages/lib/node_modules/kubycat/dist/cjs/Kubycat.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/myhome/.npm-packages/lib/node_modules/kubycat/dist/cjs/Kubycat.js:4:12)
    at Kubycat.start (/home/myhome/.npm-packages/lib/node_modules/kubycat/dist/cjs/Kubycat.js:89:16)
    at KubycatCli.main (/home/myhome/.npm-packages/lib/node_modules/kubycat/dist/cjs/KubycatCli.js:39:17) {
  code: 'ERR_FEATURE_UNAVAILABLE_ON_PLATFORM'
}

Node.js v18.17.1
```

the error brought me to [this stackoverflow](https://stackoverflow.com/questions/61806341/how-to-fix-the-feature-watch-recursively-is-unavailable-on-the-current-platform) which says that the recursive option seems unsupported on linux.

What to do? Is this just not working linux?

**Comment by schlichtanders** [comment]
Just found that not too much ago, the linux recursive features seems to have been added

**Comment by sheldonjuncker** [comment]
Thanks for finding that! I'll add in a note about Node.js version requirements, but I also found that `chokidar` or `node-watch` might be alternatives to `fs.watch` that don't have this limitation on Linux. If `chokidar` is really as easy to work with as people have said, I can switch to that too.

**Comment by schlichtanders** [comment]
Indeed it works after updating nodejs to use a 20.x version! :partying_face:
